version: '3.8'

services:
  thrift:
    image: registry.gitlab.com/alphaguard/gitlabci-runners/apache_thrift:latest
    entrypoint: ""
    command: thrift -o /data/src --gen rs /data/osquery.thrift
            
    volumes:
      - $PWD:/data
