//!  Create an osquery table plugin.

use crate::{osquery, OsqueryPlugin, RegistryName, Result};
use serde::{de, Deserialize, Deserializer};
use serde_json::Value;
use std::{collections::BTreeMap, fmt, result, sync::Arc};

/// An osquery table map.
pub type Table = Vec<BTreeMap<String, String>>;

/// Osquery table plugin. That implement the OsqueryPlugin interface
/// * [`GenFunc`]: returns the rows generated by the table. The QueryContext argument provides the
// deserialized JSON query context from osquery.
pub struct TablePlugin<GenFunc: FnMut(QueryContext) -> Result<Table>> {
    name: Arc<String>,
    registry: RegistryName,
    columns: Vec<ColumnDefinition>,
    generate: GenFunc,
}

// ColumnType is a strongly typed representation of the data type string for a
// column definition. The named constants should be used.
#[derive(Debug, Deserialize, PartialEq)]
#[serde(rename_all = "UPPERCASE")]
pub enum ColumnType {
    Text,
    Integer,
    BigInt,
    Double,
}

// The following column types are defined in osquery tables.h.
impl fmt::Display for ColumnType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self {
            ColumnType::Text => write!(f, "TEXT"),
            ColumnType::Integer => write!(f, "INTEGER"),
            ColumnType::BigInt => write!(f, "BIGINT"),
            ColumnType::Double => write!(f, "DOUBLE"),
        }
    }
}

/// QueryContext contains the constraints from the WHERE clause of the query,
/// that can optionally be used to optimize the table generation. Note that the
/// osquery SQLite engine will perform the filtering with these constraints, so
/// it is not mandatory that they be used in table generation.
/// #
/// Implements [`Deref`] & [`DerefMut`] traits on a constraints map with column name to the details
/// of the constraints on that column.
#[derive(Debug, Default)]

pub struct QueryContext(BTreeMap<String, ConstraintList>);

impl std::ops::DerefMut for QueryContext {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl std::ops::Deref for QueryContext {
    type Target = BTreeMap<String, ConstraintList>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<'de> Deserialize<'de> for QueryContext {
    fn deserialize<D>(deserializer: D) -> result::Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let mut constraints = BTreeMap::new();
        let helper: Value = Deserialize::deserialize(deserializer)?;
        match &helper["constraints"] {
            Value::Array(raw_constraints) => {
                for constraint in raw_constraints {
                    match &constraint["name"] {
                        Value::String(name) => {
                            constraints.insert(
                                name.to_string(),
                                serde_json::from_value::<ConstraintList>(constraint.clone())
                                    .map_err(de::Error::custom)?,
                            );
                        }
                        other => {
                            return Err(de::Error::custom(format!(
                                "name: invalid value {}, expected string",
                                other
                            )))
                        }
                    }
                }
                Ok(QueryContext(constraints))
            }
            Value::Null => Ok(QueryContext(constraints)),
            other => Err(de::Error::custom(format!(
                "constraints: invalid value {}, expected array",
                other
            ))),
        }
    }
}

// ConstraintList contains the details of the constraints for the given column.
#[derive(Debug, Deserialize)]
pub struct ConstraintList {
    affinity: ColumnType,
    #[serde(default, rename = "list", deserialize_with = "de_constraint_list")]
    constraints: Vec<Constraint>,
}

impl ConstraintList {
    pub fn affinity(&self) -> &ColumnType {
        &self.affinity
    }

    pub fn constraints(&self) -> &[Constraint] {
        self.constraints.as_ref()
    }
}

fn de_constraint_list<'de, D>(deserializer: D) -> result::Result<Vec<Constraint>, D::Error>
where
    D: Deserializer<'de>,
{
    let helper: Value = Deserialize::deserialize(deserializer)?;
    match helper {
        // string indicates empty list in osquery
        Value::String(s) if s.is_empty() => Ok(Vec::new()),
        val => match serde_json::from_value(val) {
            Ok::<Vec<Constraint>, _>(res) => Ok(res),
            Err(err) => Err(de::Error::custom(format!(
                "unexpected context list: {}",
                err
            ))),
        },
    }
}

// Constraint contains both an operator and an expression that are applied as
// constraints in the query.
#[derive(Debug, Deserialize)]
pub struct Constraint {
    #[serde(rename = "op")]
    operator: Operator,
    #[serde(rename = "expr")]
    expression: String,
}

impl Constraint {
    pub fn operator(&self) -> &Operator {
        &self.operator
    }

    pub fn expression(&self) -> &str {
        self.expression.as_ref()
    }
}

// Operator is an enum of the osquery operators.
// The following operators are dfined in osquery tables.h.
#[derive(Debug, PartialEq)]
pub enum Operator {
    Equals = 2,
    GreaterThan = 4,
    LessThanOrEquals = 8,
    LessThan = 16,
    GreaterThanOrEquals = 32,
    Match = 64,
    Like = 65,
    Glob = 66,
    Regexp = 67,
    Unique = 1,
    In = 3,
}

impl<'de> Deserialize<'de> for Operator {
    fn deserialize<D>(deserializer: D) -> result::Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let helper: Value = Deserialize::deserialize(deserializer)?;
        match helper {
            // osquery < v3.0 with stringy types
            Value::String(s) if !s.is_empty() => {
                let op = s.parse::<i64>().map_err(de::Error::custom)?;
                Operator::try_from(op)
                    .map_err(|_| de::Error::custom(format!("invalid value {}", op)))
            }
            // osquery > v3.0 with strong types
            Value::Number(n) if n.is_i64() => {
                let op = n
                    .as_i64()
                    .ok_or_else(|| de::Error::custom("expected an int"))?;
                Operator::try_from(op)
                    .map_err(|_| de::Error::custom(format!("invalid value {}", op)))
            }
            value => Err(de::Error::custom(format!(
                "invalid value {}, expected int",
                value,
            ))),
        }
    }
}

impl TryFrom<i64> for Operator {
    type Error = ();
    fn try_from(value: i64) -> result::Result<Self, Self::Error> {
        match value {
            x if x == Operator::Equals as i64 => Ok(Operator::Equals),
            x if x == Operator::In as i64 => Ok(Operator::In),
            x if x == Operator::GreaterThan as i64 => Ok(Operator::GreaterThan),
            x if x == Operator::LessThanOrEquals as i64 => Ok(Operator::LessThanOrEquals),
            x if x == Operator::LessThan as i64 => Ok(Operator::LessThan),
            x if x == Operator::GreaterThanOrEquals as i64 => Ok(Operator::GreaterThanOrEquals),
            x if x == Operator::Match as i64 => Ok(Operator::Match),
            x if x == Operator::Like as i64 => Ok(Operator::Like),
            x if x == Operator::Glob as i64 => Ok(Operator::Glob),
            x if x == Operator::Regexp as i64 => Ok(Operator::Regexp),
            x if x == Operator::Unique as i64 => Ok(Operator::Unique),
            _ => Err(()),
        }
    }
}

// ColumnDefinition defines the relevant information for a column in a table plugin.
pub struct ColumnDefinition {
    name: String,
    col_type: ColumnType,
}

impl ColumnDefinition {
    // helper for defining columns containing strings.
    pub fn text(name: &str) -> Self {
        Self {
            name: name.to_string(),
            col_type: ColumnType::Text,
        }
    }

    // helper for defining columns containing integers.
    pub fn integer(name: &str) -> Self {
        Self {
            name: name.to_string(),
            col_type: ColumnType::Integer,
        }
    }

    // helper for defining columns containing big integers.
    pub fn big_int(name: &str) -> Self {
        Self {
            name: name.to_string(),
            col_type: ColumnType::BigInt,
        }
    }

    // helper for defining columns containing floating point values.
    pub fn double(name: &str) -> Self {
        Self {
            name: name.to_string(),
            col_type: ColumnType::Double,
        }
    }
}

impl<GenFunc: FnMut(QueryContext) -> Result<Table>> TablePlugin<GenFunc> {
    /// creates a ConfigPlugin plugin.
    /// * [`GenFunc`]: should return a [`Result<Table>`]
    ///   returns the rows generated by the table.
    pub fn new(name: &str, columns: Vec<ColumnDefinition>, generate: GenFunc) -> Box<Self> {
        Box::new(Self {
            name: Arc::from(name.to_string()),
            registry: RegistryName::Table,
            columns,
            generate,
        })
    }
}

impl<GenFunc: FnMut(QueryContext) -> Result<Table> + Send + Sync> OsqueryPlugin
    for TablePlugin<GenFunc>
{
    fn name(&self) -> std::sync::Arc<String> {
        Arc::clone(&self.name)
    }

    fn registry_name(&self) -> &RegistryName {
        &self.registry
    }

    fn routes(&mut self) -> osquery::ExtensionPluginResponse {
        let mut routes = osquery::ExtensionPluginResponse::new();
        for col in &self.columns {
            routes.push(BTreeMap::from([
                (String::from("id"), String::from("column")),
                (String::from("name"), col.name.clone()),
                (String::from("type"), col.col_type.to_string()),
                (String::from("op"), String::from("0")),
            ]));
        }
        routes
    }

    fn call(&mut self, req: osquery::ExtensionPluginRequest) -> osquery::ExtensionResponse {
        let ok = osquery::ExtensionStatus::new(0, String::from("OK"), None);
        match req.get("action") {
            Some(action) if action == "generate" => match req.get("context") {
                Some(s) => match serde_json::from_str::<QueryContext>(s) {
                    Ok(ctx) => match (self.generate)(ctx) {
                        Ok(table) => osquery::ExtensionResponse::new(ok, table),
                        Err(err) => osquery::ExtensionResponse::new(
                            osquery::ExtensionStatus::new(
                                1,
                                format!("error generating table: {}", err),
                                None,
                            ),
                            None,
                        ),
                    },
                    Err(err) => osquery::ExtensionResponse::new(
                        osquery::ExtensionStatus::new(
                            1,
                            format!("error parsing context JSON: {}", err),
                            None,
                        ),
                        None,
                    ),
                },
                None => osquery::ExtensionResponse::new(
                    osquery::ExtensionStatus::new(1, String::from("query context is nil"), None),
                    None,
                ),
            },
            Some(action) if action == "columns" => {
                osquery::ExtensionResponse::new(ok, self.routes())
            }
            Some(action) => osquery::ExtensionResponse::new(
                osquery::ExtensionStatus::new(1, format!("unknown action: {}", action), None),
                None,
            ),
            None => osquery::ExtensionResponse::new(
                osquery::ExtensionStatus::new(1, String::from("action is nil"), None),
                None,
            ),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_plugin() {
        let status_ok = osquery::ExtensionStatus::new(0, String::from("OK"), None);
        let mut called_query_ctx = QueryContext::default();
        let mut plugin = TablePlugin::new(
            "mock",
            vec![
                ColumnDefinition::text("text"),
                ColumnDefinition::integer("integer"),
                ColumnDefinition::big_int("big_int"),
                ColumnDefinition::double("double"),
            ],
            |qctx| {
                called_query_ctx = qctx;
                Ok(vec![BTreeMap::from([
                    ("text".to_string(), "hello world".to_string()),
                    ("integer".to_string(), "123".to_string()),
                    ("big_int".to_string(), "-1234567890".to_string()),
                    ("double".to_string(), "3.14159".to_string()),
                ])])
            },
        );

        let tresp = vec![
            BTreeMap::from([
                (String::from("id"), String::from("column")),
                (String::from("name"), String::from("text")),
                (String::from("type"), String::from("TEXT")),
                (String::from("op"), String::from("0")),
            ]),
            BTreeMap::from([
                (String::from("id"), String::from("column")),
                (String::from("name"), String::from("integer")),
                (String::from("type"), String::from("INTEGER")),
                (String::from("op"), String::from("0")),
            ]),
            BTreeMap::from([
                (String::from("id"), String::from("column")),
                (String::from("name"), String::from("big_int")),
                (String::from("type"), String::from("BIGINT")),
                (String::from("op"), String::from("0")),
            ]),
            BTreeMap::from([
                (String::from("id"), String::from("column")),
                (String::from("name"), String::from("double")),
                (String::from("type"), String::from("DOUBLE")),
                (String::from("op"), String::from("0")),
            ]),
        ];

        assert_eq!(plugin.name().as_str(), "mock");
        assert_eq!(*plugin.registry_name(), RegistryName::Table);
        assert_eq!(tresp, plugin.routes());

        // Call explicit columns action
        let resp = plugin.call(osquery::ExtensionPluginRequest::from([(
            String::from("action"),
            String::from("columns"),
        )]));
        assert_eq!(resp.status.unwrap(), status_ok);
        assert_eq!(tresp, resp.response.unwrap());

        // Call with good action and context
        let resp = plugin.call(osquery::ExtensionPluginRequest::from([
            (String::from("action"), String::from("generate")),
            (String::from("context"), String::from("{}")),
        ]));
        assert_eq!(resp.status.unwrap(), status_ok);
        assert_eq!(called_query_ctx.len(), QueryContext::default().len());
        assert_eq!(
            vec![BTreeMap::from([
                (String::from("big_int"), String::from("-1234567890")),
                (String::from("double"), String::from("3.14159")),
                (String::from("integer"), String::from("123")),
                (String::from("text"), String::from("hello world")),
            ]),],
            resp.response.unwrap()
        );
    }

    #[test]
    fn table_plugin_errors() {
        let mut called = 0;
        let mut plugin = TablePlugin::new(
            "mock",
            vec![
                ColumnDefinition::text("text"),
                ColumnDefinition::integer("integer"),
                ColumnDefinition::big_int("big_int"),
                ColumnDefinition::double("double"),
            ],
            |_| {
                called += 1;
                Err("foobar".into())
            },
        );
        assert_eq!(
            1,
            plugin
                .call(osquery::ExtensionPluginRequest::new())
                .status
                .unwrap()
                .code
                .unwrap()
        );
        assert_eq!(
            1,
            plugin
                .call(osquery::ExtensionPluginRequest::from([(
                    String::from("action"),
                    String::from("bad")
                )]))
                .status
                .unwrap()
                .code
                .unwrap()
        );
        // Call with good action but generate fails bad context
        assert_eq!(
            1,
            plugin
                .call(osquery::ExtensionPluginRequest::from([
                    (String::from("action"), String::from("generate")),
                    (String::from("context"), String::from("{[]}"))
                ]))
                .status
                .unwrap()
                .code
                .unwrap()
        );
        // Call with good action but generate fails bad table
        let resp = plugin.call(osquery::ExtensionPluginRequest::from([
            (String::from("action"), String::from("generate")),
            (String::from("context"), String::from("{}")),
        ]));
        assert_eq!(1, resp.status.clone().unwrap().code.unwrap());
        assert_eq!(
            "error generating table: foobar".to_string(),
            resp.status.unwrap().message.unwrap()
        );
        assert_eq!(called, 1, "generate should have been called only once");
    }

    #[test]
    fn column_type() {
        let test_cases = vec![
            (ColumnType::BigInt, r#"{ "affinity":"BIGINT" }"#),
            (ColumnType::Double, r#"{  "affinity":"DOUBLE" }"#),
            (ColumnType::Integer, r#"{ "affinity":"INTEGER" }"#),
            (ColumnType::Text, r#"{ "affinity":"TEXT" }"#),
        ];
        for (typ, data) in test_cases {
            let p: BTreeMap<String, ColumnType> = serde_json::from_str(data).unwrap();
            assert_eq!(typ, *p.get("affinity").unwrap());
        }
    }

    #[test]
    fn operator() {
        let test_cases = vec![
            // from int
            (false, Operator::Equals, r#"{ "op": 2 }"#),
            (false, Operator::GreaterThan, r#"{  "op": 4 }"#),
            (false, Operator::LessThanOrEquals, r#"{ "op": 8 }"#),
            (false, Operator::LessThan, r#"{ "op": 16 }"#),
            (false, Operator::GreaterThanOrEquals, r#"{ "op": 32 }"#),
            (false, Operator::Match, r#"{ "op": 64 }"#),
            (false, Operator::Like, r#"{ "op": 65 }"#),
            (false, Operator::Glob, r#"{ "op": 66 }"#),
            (false, Operator::Regexp, r#"{ "op": 67 }"#),
            (false, Operator::Unique, r#"{ "op": 1 }"#),
            (true, Operator::Unique, r#"{ "op": 9999 }"#),
            // from &str
            (false, Operator::Equals, r#"{ "op": "2" }"#),
            (false, Operator::GreaterThan, r#"{  "op": "4" }"#),
            (false, Operator::LessThanOrEquals, r#"{ "op": "8" }"#),
            (false, Operator::LessThan, r#"{ "op": "16" }"#),
            (false, Operator::GreaterThanOrEquals, r#"{ "op": "32" }"#),
            (false, Operator::Match, r#"{ "op": "64" }"#),
            (false, Operator::Like, r#"{ "op": "65" }"#),
            (false, Operator::Glob, r#"{ "op": "66" }"#),
            (false, Operator::Regexp, r#"{ "op": "67" }"#),
            (false, Operator::Unique, r#"{ "op": "1" }"#),
            (true, Operator::Unique, r#"{ "op": "9999" }"#),
        ];
        for (should_err, typ, data) in test_cases {
            let op: result::Result<BTreeMap<String, Operator>, _> = serde_json::from_str(data);
            match op {
                Ok(p) => {
                    assert!(!should_err);
                    assert_eq!(typ, *p.get("op").unwrap());
                }
                Err(e) => {
                    assert!(e.to_string().contains("9999"));
                    assert!(should_err);
                }
            }
        }
        let invalid_op = r#"{ "op": [] }"#;
        let op: result::Result<BTreeMap<String, Operator>, _> = serde_json::from_str(invalid_op);
        op.expect_err("should be invalid operator value");
    }

    #[test]
    fn deserialize_constraint_list() {
        // (test_case (should_err, json, Vec<Constraint>))
        let test_cases = vec![
            (true, r#"bad"#, None),
            (true, r#"{"foo": "bar"}"#, None),
            (false, r#"{"affinity":"BIGINT"}"#, Some(Vec::new())),
            (
                false,
                r#"{"affinity":"BIGINT", "list": "" }"#,
                Some(Vec::new()),
            ),
            (
                false,
                r#"{"affinity":"BIGINT", "list": [{"op":"2","expr":"foo"}] }"#,
                Some(vec![Constraint {
                    operator: Operator::Equals,
                    expression: "foo".to_string(),
                }]),
            ),
        ];
        for (should_err, data, constraints) in test_cases {
            match serde_json::from_str(data) {
                Ok::<ConstraintList, _>(val) => {
                    assert!(!should_err);
                    if let Some(s) = val.constraints.first() {
                        assert_eq!(
                            s.expression,
                            constraints.unwrap().first().unwrap().expression
                        )
                    };
                }
                Err(_) => assert!(should_err),
            }
        }
    }

    #[test]
    fn deserialize_query_context() {
        // (test_case (should_err, json, Vec<Constraint>))
        let test_cases = vec![
            (true, r#"bad"#, None),
            (false, r#"{"foo": "bar"}"#, Some(BTreeMap::new())),
            (
                false,
                r#"
                {"constraints": [
                    {
                        "name":"double",
                        "list":"",
                        "affinity":"DOUBLE"
                      }
                ]}
            "#,
                Some(BTreeMap::from([(
                    "double".to_string(),
                    ConstraintList {
                        affinity: ColumnType::Double,
                        constraints: vec![],
                    },
                )])),
            ),
            (
                false,
                r#"
                {"constraints": [
                    {
                        "name":"big_int",
                        "list":[{"op":"2","expr":"foo"}],
                        "affinity":"BIGINT"
                      }
                ]}
            "#,
                Some(BTreeMap::from([(
                    "big_int".to_string(),
                    ConstraintList {
                        affinity: ColumnType::BigInt,
                        constraints: vec![Constraint {
                            operator: Operator::Equals,
                            expression: "foo".to_string(),
                        }],
                    },
                )])),
            ),
            (
                false,
                r#"
                {"constraints": [
                    {
                        "name":"big_int",
                        "list":"",
                        "affinity":"BIGINT"
                    },
                    {
                        "name":"text",
                        "list":"",
                        "affinity":"TEXT"
                    }
                ]}
            "#,
                Some(BTreeMap::from([
                    (
                        "big_int".to_string(),
                        ConstraintList {
                            affinity: ColumnType::BigInt,
                            constraints: vec![],
                        },
                    ),
                    (
                        "text".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![],
                        },
                    ),
                ])),
            ),
        ];
        for (should_err, data, constraints) in test_cases {
            match serde_json::from_str::<QueryContext>(data) {
                Ok(ctxs) => {
                    assert!(!should_err);
                    let constraints = &constraints.unwrap();
                    for k in constraints.keys() {
                        assert!(ctxs.contains_key(k));
                        assert_eq!(
                            constraints.get(k).unwrap().constraints.len(),
                            ctxs.get(k).unwrap().constraints.len()
                        )
                    }
                }
                Err(_) => assert!(should_err),
            }
        }
    }

    #[test]
    fn deserialize_varying_query_contexts() {
        let test_cases = vec![
            // Stringy JSON from osquery version < 3
            (
                false,
                r#"{"constraints":[{"name":"domain","list":[{"op":"2","expr":"osquery_rs.co"}],"affinity":"TEXT"},{"name":"email","list":"","affinity":"TEXT"}]}"#,
                Some(BTreeMap::from([
                    (
                        "domain".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![Constraint {
                                operator: Operator::Equals,
                                expression: "osquery_rs.co".to_string(),
                            }],
                        },
                    ),
                    (
                        "email".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![],
                        },
                    ),
                ])),
            ),
            // Strongly typed JSON from osquery version > 3
            (
                false,
                r#"{"constraints":[{"name":"domain","list":[{"op":2,"expr":"osquery_rs.co"}],"affinity":"TEXT"},{"name":"email","list":[],"affinity":"TEXT"}]}"#,
                Some(BTreeMap::from([
                    (
                        "domain".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![Constraint {
                                operator: Operator::Equals,
                                expression: "osquery_rs.co".to_string(),
                            }],
                        },
                    ),
                    (
                        "email".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![],
                        },
                    ),
                ])),
            ),
            // Stringy
            (
                false,
                r#"{"constraints":[{"name":"path","list":[{"op":"65","expr":"%foobar"}],"affinity":"TEXT"},{"name":"query","list":[{"op":"2","expr":"kMDItemFSName = \"google*\""}],"affinity":"TEXT"}]}"#,
                Some(BTreeMap::from([
                    (
                        "path".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![Constraint {
                                operator: Operator::Like,
                                expression: "%foobar".to_string(),
                            }],
                        },
                    ),
                    (
                        "query".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![Constraint {
                                operator: Operator::Equals,
                                expression: "kMDItemFSName = \"google*\"".to_string(),
                            }],
                        },
                    ),
                ])),
            ),
            // Strong
            (
                false,
                r#"{"constraints":[{"name":"path","list":[{"op":65,"expr":"%foobar"}],"affinity":"TEXT"},{"name":"query","list":[{"op":2,"expr":"kMDItemFSName = \"google*\""}],"affinity":"TEXT"}]}"#,
                Some(BTreeMap::from([
                    (
                        "path".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![Constraint {
                                operator: Operator::Like,
                                expression: "%foobar".to_string(),
                            }],
                        },
                    ),
                    (
                        "query".to_string(),
                        ConstraintList {
                            affinity: ColumnType::Text,
                            constraints: vec![Constraint {
                                operator: Operator::Equals,
                                expression: "kMDItemFSName = \"google*\"".to_string(),
                            }],
                        },
                    ),
                ])),
            ),
            // Error cases
            (true, r#"{bad json}"#, None),
            (
                true,
                r#"{"constraints":[{"name":"foo","list":["bar", "baz"],"affinity":"TEXT"}]"#,
                None,
            ),
        ];
        for (should_err, data, constraints) in test_cases {
            match serde_json::from_str::<QueryContext>(data) {
                Ok(ctxs) => {
                    assert!(!should_err);
                    let constraints = &constraints.unwrap();
                    for k in constraints.keys() {
                        assert!(ctxs.contains_key(k));
                        assert_eq!(
                            constraints.get(k).unwrap().constraints.len(),
                            ctxs.get(k).unwrap().constraints.len()
                        );
                        match ctxs.get(k).unwrap().constraints.first() {
                            Some(cnt) => {
                                assert_eq!(
                                    cnt.expression,
                                    ctxs.get(k).unwrap().constraints.first().unwrap().expression
                                );
                                assert_eq!(
                                    cnt.operator,
                                    ctxs.get(k).unwrap().constraints.first().unwrap().operator
                                );
                            }
                            None => {
                                assert!(constraints.get(k).unwrap().constraints.first().is_none())
                            }
                        };
                    }
                }
                Err(_) => assert!(should_err),
            }
        }
    }
}
